languageCode = "en"
languageName = "English"
weight = 1
title = "What's the Problem?"

[params]
displayName = "EN"
isoCode = "en"
rtl = false
dateFormat = "2 January 2006"
logo = "images/logo.png"
description = "Some of the most inspirational entrepreneurs we have met are driven by the problem they are trying to solve, not by their product. In each episode we speak to entrepreneurs, to dig into pain points and to identify gaps in the market."

[author]
name = "What's the Problem?"
headline = "Some of the most inspirational entrepreneurs we have met are driven by the problem they are trying to solve, not by their product. In each episode we speak to entrepreneurs, to dig into pain points and to identify gaps in the market."
links = [
  { linkedin = "https://example.com/" },
  { instagram = "https://example.com/" },
  { tiktok = "https://example.com/" },
]
