baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'My New Hugo Site'

[[menus.main]]
name = 'Episodes'
pageRef = '/episodes'
weight = 10

[[menus.main]]
name = 'Advisory'
pageRef = '/advisory'
weight = 20

[[menus.main]]
name = 'Services'
pageRef = '/advisory/services'
parent = 'Advisory'
weight = 1

[[menus.main]]
name = 'Projects'
pageRef = '/advisory/projects'
parent = 'Advisory'
weight = 2

[[menus.main]]
name = 'About'
pageRef = '/about'
weight = 30

[[menus.main]]
name = 'WtP'
pageRef = '/about/whats-the-problem'
parent = 'About'
weight = 1

[[menus.main]]
name = 'The Hosts'
pageRef = '/about/the-hosts'
parent = 'About'
weight = 2

[[menus.main]]
name = 'Contact'
pageRef = '/about/contact'
parent = 'About'
weight = 3

[[menus.main]]
name = 'Companies'
pageRef = '/companies'
weight = 40

[[menus.main]]
name = 'Guests'
pageRef = '/companies/guests'
parent = 'Companies'
weight = 1

[[menus.main]]
name = 'Portfolio'
pageRef = '/companies/portfolio'
parent = 'Companies'
weight = 2

[[menus.main]]
name = 'Partners'
pageRef = '/companies/partners'
parent = 'Companies'
weight = 3

[module]
  [module.hugoVersion]
    extended = false
    min = "0.116.0"
